export const getCategoryConfigs = () => ({
  'agri-basics': {
    name: '農業基礎入門',
    description: '農業基礎知識與入門概念',
    icon: '🌱',
    color: '#22c55e',
    colorLight: '#22c55e20',
    gradient: 'linear-gradient(135deg, #22c55e, #4ade80)',
    cover: '',
  },
  'agri-advanced': {
    name: '農業進階實務',
    description: '進階農業技術與實務應用',
    icon: '🌾',
    color: '#16a34a',
    colorLight: '#16a34a20',
    gradient: 'linear-gradient(135deg, #16a34a, #22c55e)',
    cover: '',
  },
  'farm-management': {
    name: '農場經營管理',
    description: '農場經營策略與管理方法',
    icon: '🏡',
    color: '#ca8a04',
    colorLight: '#ca8a0420',
    gradient: 'linear-gradient(135deg, #ca8a04, #eab308)',
    cover: '',
  },
  'crop-production': {
    name: '作物生產技術',
    description: '作物栽培與生產技術',
    icon: '🌿',
    color: '#15803d',
    colorLight: '#15803d20',
    gradient: 'linear-gradient(135deg, #15803d, #22c55e)',
    cover: '',
  },
  'facility-farming': {
    name: '設施農業',
    description: '設施農業技術與溫室管理',
    icon: '🏗️',
    color: '#0891b2',
    colorLight: '#0891b220',
    gradient: 'linear-gradient(135deg, #0891b2, #06b6d4)',
    cover: '',
  },
  'smart-farming': {
    name: '智慧農業',
    description: '智慧農業與數位科技應用',
    icon: '🤖',
    color: '#2563eb',
    colorLight: '#2563eb20',
    gradient: 'linear-gradient(135deg, #2563eb, #3b82f6)',
    cover: '',
  },
  'agri-marketing': {
    name: '農產品銷售',
    description: '農產品行銷與銷售策略',
    icon: '📦',
    color: '#ea580c',
    colorLight: '#ea580c20',
    gradient: 'linear-gradient(135deg, #ea580c, #f97316)',
    cover: '',
  },
  'grants-planning': {
    name: '計畫撰寫補助',
    description: '補助計畫撰寫與申請',
    icon: '📝',
    color: '#7c3aed',
    colorLight: '#7c3aed20',
    gradient: 'linear-gradient(135deg, #7c3aed, #a855f7)',
    cover: '',
  },
  'field-visits': {
    name: '場域交流觀摩',
    description: '農場參訪與交流觀摩',
    icon: '🚜',
    color: '#b45309',
    colorLight: '#b4530920',
    gradient: 'linear-gradient(135deg, #b45309, #f59e0b)',
    cover: '',
  },
  'livestock-health': {
    name: '畜牧健康',
    description: '畜牧管理與動物健康',
    icon: '🐄',
    color: '#dc2626',
    colorLight: '#dc262620',
    gradient: 'linear-gradient(135deg, #dc2626, #ef4444)',
    cover: '',
  },
});

const __plainCategoryConfig = getCategoryConfigs();

export const categoryList = Object.keys(__plainCategoryConfig) as CategoryKey[];
export type CategoryKey = keyof typeof __plainCategoryConfig;
